services:
  - type: web
    name: asked-backend
    env: java
    plan: free
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
    rootDir: backend
