services:
  - type: web
    name: asked-backend
    env: java
    buildCommand: "./.render/build.sh"
    startCommand: "java -jar target/backend-0.0.1-SNAPSHOT.jar"
    plan: free
    envVars:
      - key: JAVA_VERSION
        value: 17
